### PR TITLE
Update to allow Vite 5

### PR DESCRIPTION
**Pull request by maxfenton**
- https://github.com/davidwebca/vite-plugin-hmr-public-copy/issues/1

Update package.json to allow installation with Vite 5

### CODE REVIEW

**Comment by maxfenton** [comment]
When I make this change locally, I'm able to proceed with `npm install`

Updating my vite config like this **works**:
`import ViteHmrPublicCopy from "vite-plugin-hmr-public-copy/src/index.mjs";`

Updating my vite config like this:
`import ViteHmrPublicCopy from "vite-plugin-hmr-public-copy/dist/index.mjs";`
— throws an error: `Dynamic require of "util" is not supported`:

Updating my vite config like this:
`import ViteHmrPublicCopy from "vite-plugin-hmr-public-copy/dist/index.cjs";`
or this:
`import ViteHmrPublicCopy from "vite-plugin-hmr-public-copy";`
— throws an error: `ViteHmrPublicCopy is not a function`:

**Comment by maxfenton** [comment]
@davidwebca If you're able to merge this peerDependency change, I'd be happy to keep working on figuring out additional fixes and refactoring about the cjs/mjs but otherwise, I need to pull this package from all my Vite 5 projects and find another way to do the same thing this package does.

**Comment by davidwebca** [comment]
Yep, sorry I've kept you waiting, I was sick but better now. I'll test on my project right away.

**Comment by maxfenton** [comment]
No problem! Thank you so much. I have time to test this on a few Vite 5 projects alongside Vite 4 projects.

**Comment by davidwebca** [comment]
Update: Everything's fixed and working on my end. Only had to upgrade some dependencies, explicitly declare exports in package.json so that esm and cjs are imported properly by vite. I've tagged 1.0.0 to avoid breaking people's setup so Vite 5 requires ^1.0.0. Let me know if there's any issues in your project by opening separate issues or making separate pull requests. 🤘🏻

**Pull request merged**
